### ISSUE TITLE
Implement feedback process at the end

### ISSUE THREAD

**Issue by jochenpilger** [bet-smart-parking/smart-parking-frontend#38]
Link to the survey: https://docs.google.com/forms/d/e/1FAIpQLSdlnDWce1kbgVeoT_x-qBmWjXlsgR9CqTuCAIYWf41WnKQJng/viewform

- integrate this link into the success page (check [prototype](https://www.figma.com/file/ugzf5ZRhOVqPVcDkL6MKMl/ProtoType-v2?node-id=0%3A1))

- integrate this link into the SMS with the receipt (check [prototype](https://www.figma.com/file/ugzf5ZRhOVqPVcDkL6MKMl/ProtoType-v2?node-id=0%3A1))

**Comment by hirsch88** [comment]
done
